name: test cicd

on:
  push:
    branches: ["main"]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: package with maven
        run: mvn package
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
  docker:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v4
      - name: downlload artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: app
        
  
          
        




